spring:
  data:
    redis:
      uri: redis-cli -u redis://default:sPCPxWzdBygAMrS8S4Ctar4u59ZYaq15@redis-10992.crce286.ap-south-1-1.ec2.cloud.redislabs.com:10992

    mongodb:
      uri: mongodb+srv://ng985623_db_user:S1mCwwHKa7yQoe7X@cluster0.v6qgzxz.mongodb.net/journaldb?retryWrites=true&w=majority
      auto-index-creation: true

  config:
    activate:
      on-profile: prod