server:
  port: ${PORT:8081}

spring:
  profiles:
    active: dev   # prod baad me use kar

  data:
    mongodb:
      uri: mongodb+srv://ng985623_db_user:S1mCwwHKa7yQoe7X@cluster0.v6qgzxz.mongodb.net/journaldb?retryWrites=true&w=majority
      auto-index-creation: true

    redis:
      uri: redis://default:sPCPxWzdBygAMrS8S4Ctar4u59ZYaq15@redis-10992.crce286.ap-south-1-1.ec2.cloud.redislabs.com:10992

  mail:
    host: smtp.gmail.com
    port: 587
    username: neerajgupta962150@gmail.com
    password: vhihhcbtilimtgxl
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
          ssl:
            trust: smtp.gmail.com

  kafka:
    bootstrap-servers: localhost:9092

    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

    consumer:
      group-id: weekly-sentiment-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring:
          json:
            trusted:
              packages: "*"
            value:
              default:
                type: com.edigest.my.first.project.sentiment.SentimentData

weather:
  api:
    key: e872ed94a87e412ea2390557262602